name: Alpha
description: Alphs template for Jekyll
baseurl: '/Alpha-Jekyll-Theme'

url: "http://localhost:4000"

paginate: 10

# Author Settings
author: Scott Holden & Ravi Kaur # add your name
author-img:  # add your photo
about-author: Azure VMware Solutions Global Black Belts. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address
